name: Build and validate PR
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup and validate themes
        uses: ./.github/actions/setup-and-validate
